# This is a basic workflow to help you get started with Actions

name: CI

env:
  IMAGE_NAME: poddy


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Cache packages
        uses: actions/cache@v3
        with:
            path: |
              /home/runner/.local/share/containers
            key: no

      - name: Build with buildah
        run: |
          ctr=$(buildah from "archlinux")
          buildah config \
            --cmd /usr/bin/ls $ctr
          buildah run "$ctr" -- pacman \
            --noconfirm -Syu
          buildah commit -- "$ctr" "$IMAGE_NAME"
          buildah rm "$ctr"

      - run: podman images


      - name: Run podman
        run: |
          podman run \
            --mount type=bind,src=${GITHUB_WORKSPACE},dst=/root/,Z "$IMAGE_NAME"



      - name: done
        run: echo "done"
